version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    tty: true
    ports:
      - 8000:80
    volumes:
      - ./nginxconfig/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - traefik-public
  frontend:
    image: node:19.1.0-alpine
    working_dir: /app
    command: sh -c "yarn install && yarn run dockerdev"
    ports:
      - "4444:4444"
      - "24678:24678"
    volumes: 
      - type: bind
        source: "."
        target: /app
    networks:
      - traefik-public
  backend:
    image: node:19.1.0-alpine
    working_dir: /app
    command: sh -c "yarn install && yarn run dev"
    networks: 
      - traefik-public
    ports:
      - "4445:4445"
    volumes: 
      - type: bind
        source: ./api/
        target: /app
    environment: 
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  db:
    image: mariadb
    restart: on-failure
    container_name: dbcontainer
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: database
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks: 
      - traefik-public
    volumes: 
      - ./mariadb:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports: 
      - 4446:8080
    networks:
      - traefik-public
networks:
 traefik-public:
    name: traefik-public
